baseURL = 'https://konradhalas.pl/'
languageCode = 'en-us'
title = 'Konrad Hałas'
theme = 'typo'

[params]
description = 'Konrad Hałas personal website.'
breadcrumbs = true
homeIntroTitle = 'Hi!'
homeIntroContent = """
Hi, my name is Konrad, and I'm happy to see you on my personal homepage.

On this site, you'll find a few words [about me](/about), a list of my current and past [projects](/projects), and the [talks](/talks) I've given. Feel free to [contact](/contact) me if you have any questions or just want to chat.

Enjoy exploring!
"""

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "talks"
url = "/talks"

[[params.menu]]
name = "contact"
url = "/contact"

[[params.social]]
name = "github"
url = "https://github.com/konradhalas"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/konradhalas"
